name: 'Wait on check'
description: 'Wait on a certain check to pass for commit'
inputs:
  allowed-conclusions:
    description: 'Array of allowed conclusions'
    required: false
    default: success,skipped
  ignore-checks:
    description: 'Array of ignore checks'
    required: false
    default: ''
  check-name:
    description: 'A name of a check that has to pass'
    required: false
    default: ''
  check-regexp:
    description: 'Filter checks to wait using Regexp'
    required: false
    default: ''
  ref:
    description: 'A git ref to be checked: branch/tag/commit sha'
    required: true
  repo-token:
    description: 'A GitHub token for the repo'
    required: false
    default: ''
  wait-interval:
    description: 'Seconds to wait between Checks API requests'
    required: false
    default: '10'
  api-endpoint:
    description: 'Github API Endpoint to use.'
    required: false
    default: ''
  running-workflow-name:
    description: 'Name of the workflow to be ignored (the one who is waiting for the rest)'
    required: false
    default: ''
  verbose:
    description: 'Print logs if true'
    required: false
    default: 'true'
  fail-on-no-checks:
    description: 'Fail the action if no checks match the filter (check-name or check-regexp). Set to false to succeed when no checks match.'
    required: false
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'green'
